id: IC23875D7
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:01:00.929250
last_modified: 2023-02-08 15:01:00.929450
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: sa
bases:
  4AD4:
    base_file: 4AD4.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
